### PR TITLE
Automatically grow/shrink ArrayField from updates

### PR DESCRIPTION
**Pull request by MikeDombo**
Resolving https://github.com/joepuzzo/informed/issues/226

### CODE REVIEW

**Comment by joepuzzo** [comment]
Can you heavily comment the code to explain what exactly it is your doing. What are defferedUpdates. How are they used.

**Comment by MikeDombo** [comment]
Added inline comments explaining what is going on in each stage and why.

**Comment by joepuzzo** [comment]
Hmm I need to take more time to digest this but it seems over complex. Im not following the recursive function. Whats recursive about an array field. The data should simply drive the content on the page on a rerender. We should not have to worry about deferring updates.

**Comment by joepuzzo** [comment]
Also this looks like its assuming you can set the value of an array field which you cant. An array field is special as its a "shadow" field. Its acts like a field but is not itself an actual field because there is no input tied directly to it.

**Pull request closed without merging**
