### PR TITLE
Fixed showErrorIfTouched

### PR DESCRIPTION
**Pull request by Bezmehrabi**

### CODE REVIEW

**Comment by joepuzzo** [comment]
I dont understand why this is needed? can you explain? the default is showError if touched, so why do we need that last check ?

**Comment by Bezmehrabi** [comment]
If you pass the `showErrorIfTouched: false, showErrorIfError: false, showErrorIfDirty: false`, the error will still show up on `touched`, so the `showErrorIfTouched` property has no effect whether you give `true` or `false`.

**Comment by joepuzzo** [comment]
Ok so you never want the error to show then ?

**Comment by Bezmehrabi** [comment]
yeah, in our situation, the error message doesn't matter. we just want to make the input border red when there is an error.

it's a rare situation, but yeah...

**Comment by joepuzzo** [comment]
but red border uses same boolean?

**Comment by Bezmehrabi** [comment]
nah, it uses the `fieldState.error` value.

I think we will need to set the value of `showErrorIfTouched` in [formControllerOptions](https://github.com/joepuzzo/informed/blob/7c2272de3968603406f04aae319f6c66f6babfdf/src/hooks/useForm.js#L43) to `true`, so by default the errors will show up on `touched`, but users can disable it with passing `showErrorIfTouched: false`, am I right?

**Comment by joepuzzo** [comment]
Ok I just pulled PR and am adding that part now

**Comment by joepuzzo** [comment]
Im also adding unit tests for this

**Comment by Bezmehrabi** [comment]
Awesome!

**Comment by joepuzzo** [comment]
https://github.com/joepuzzo/informed/pull/367 See new PR here

**Pull request closed without merging**
