### PR TITLE
Update FormController settings; fixes #59

### LINKED ISSUE #59: Unable to change external reference for 'onSubmit' from a Rerender
`<Form className={classes.form} onSubmit={e => (isRegistration ? register(e, this.state) : login(e, this.state)) } >`

### PR DESCRIPTION
**Pull request by peternoordijk**
Hi! First of all, thank you very much for creating this library. It really is a big timesaver.

I created this pull request because of issue #59 , but I will elaborate a bit as this issue doesn't have such a clear description.

```js
class SomeComponent extends Component {
  constructor(props) {
    super(props);
    this.state = { triggered: false };
  }

  componentDidMount() {
    setTimeout(() => this.setState({
      triggered: true
    }), 1000);
  }

  onInitialSubmit() {
    // This will be called
  }

  onSecondSubmit() {
    // This will never be called
  }

  render() {
    const { triggered } = this.state;
    if (!triggered) {
      return (
        <Form 
          onSubmit={this.onInitialSubmit} 
          id="form-one"
        >
          ...
        </Form>
      );
    }
    return (
      <Form 
        onSubmit={this.onSecondSubmit} 
        id="form-two"
      >
        ...
      </Form>
    );
  }
}
```

Basically it was impossible to change the hooks and basic configuration after mounting the `Form` for the first time. This PR fixes that.

### CODE REVIEW

**Comment by joepuzzo** [comment]
Looking into this now!

**Comment by joepuzzo** [comment]
Hey Can you add this test and other tests to the Form.spec. I created a template test for ya

```jsx

  /* ---------- The following class will be used for some of the tests below ---------- */

  class SomeComponent extends Component {
    constructor(props) {
      super(props);
      this.state = { triggered: false };
    }
  
    componentDidMount() {
      setTimeout(() => this.setState({
        triggered: true
      }), 1000);
    }
  
    render() {
      const { triggered } = this.state;
      const { submit1, submit2 } = this.props;
      return (
        <Form onSubmit={ triggered ? submit2 : submit1 }>
          <Text field="greeting" />
          <button type="submit">Submit</button>
        </Form>
      );
    }
  }

  it('should call correct onSubmit function with values when the form is submitted after updating onSubmit externally', done => {
    const spy1 = sandbox.spy();
    const spy2 = sandbox.spy();
    const wrapper = mount(
      <SomeComponent submit1={spy1} submit2={spy2} />
    );

    setTimeout(()=>{
      const input = wrapper.find('input');
      input.simulate('change', { target: { value: 'hello' } });
      const button = wrapper.find('button');
      button.simulate('submit');
      setImmediate(() => {
        expect(spy1.called).to.equal(false);
        expect(spy2.called).to.equal(true);
        expect(spy2.args[0][0]).to.deep.equal({ greeting: 'hello' });
        done();
      });
    }, 1500);

  });
```

**Comment by peternoordijk** [comment]
Awesome! I will add a unit test when I have the chance to work on it-- probably in a couple hours. Thanks for the template!

**Comment by peternoordijk** [comment]
I hope you don't mind the delay... I hope I'll be able to do this tomorrow or in the weekend 🙂

**Comment by joepuzzo** [comment]
Any updates on this?

**Pull request closed without merging**
