### PR TITLE
fix(asField): return `required` in `userProps`

### LINKED ISSUE #330: `asField` not returning `required` to custom component
Given:

```jsx
const CustomField = asField({required}) => {
	return <input {required} />
}

<CustomField required={true} />
```

I would expect `input.getAttribute('required') === true`.

Instead, `input.getAttribute('required') === undefined` as a result of https://github.com/joepuzzo/informed/commit/2de4eceaf5d2d84bb10db9fe8232646fda5aef90#diff-0231c368f89794c64e7bc2db83761f86348f5f651442db34d3b71b89f88ae432.

### Suggestion:

- return `required` in `userProps`.

### PR DESCRIPTION
**Pull request by larrybotha**
added tests for `id` and `multiple` attributes, too

closes #330

### CODE REVIEW

**Comment by joepuzzo** [comment]
I actually cant merge this and need to think it through. because required passed to the dom element will trigger browser validation in chrome and that messes up informed's validation.

**Comment by larrybotha** [comment]
@joepuzzo is this specifically for the fields made available by informed that use `asField` / `useField`?

In my scenario I have custom components that use `asField` and rely on `required` (they've done so before `required` was stripped on a more recent version of informed). I don't use `required` on the DOM element itself, because of the validation issue, but I use it to determine whether the label should indicate a field is optional or not.

If I may propose an approach:

- for informed fields, strip out `required` before spreading the props onto the DOM element
	- a user can expect that informed's custom fields validate as they expect
	- if the user _has_ to have access to the `required` attribute on a field, or potentially any other property they pass in which may or may not be stripped by an informed component, then they can use `asField` or `useField` and build their own custom component
- for custom components, the user has access to all the properties they pass through
	- if they happen to spread `required` onto a DOM element, they can expect informed's validation not to work. A note somewhere in the docs may be valuable here for when users may be confused about this
	- this is less surprising than a prop that's suddenly missing
	- the user can maintain full consistency of properties on custom inputs and DOM inputs

Are there any specific issues I'm overlooking? I'd be happy to submit a PR (with tests) where `required` is stripped from informed's fields!

**Comment by joepuzzo** [comment]
Problem is this would be a breaking change for people that spread `userProps` on already custom fields..

**Comment by joepuzzo** [comment]
In other words Yes the solution would work if I took it out manually for informeds default fields. But 90% of people that use this have already wrapped their custom fields and spread user props

**Comment by larrybotha** [comment]
Ye, there was a change somewhere between 3.9.0 and 3.29.0 that broke my custom components with the stripping of `required` :/

Ok cool, that makes sense. I'll make a plan on my side in the meanwhile.

Is there anything I can do to assist? I know versioning and releases can be a mission - I'll be happy to implement `semantic-release` which is great for automating versioning if that'll remove some overhead for you and other maintainers.

**Pull request closed without merging**
