### PR TITLE
fixed code example in README.md

### PR DESCRIPTION
**Pull request by alexandrtovmach**
Small fix of typos in code example

### CODE REVIEW

**Comment by joepuzzo** [comment]
Realized i already fixed this and fogot to close my bad

**Comment by alexandrtovmach** [comment]
@joepuzzo ammm... but you're not fixed....

**Comment by joepuzzo** [comment]
??

**Comment by alexandrtovmach** [comment]
This PR should update README.md, but you've closed it in reason that already fixed, but it's not.

image

**Comment by joepuzzo** [comment]
Ooos it was a different readme that i had fixed my bad i will pull in

**Comment by alexandrtovmach** [comment]
Yeeey, nice. Good job 🙏

**Pull request merged**
