### PR TITLE
improved typing

### PR DESCRIPTION
**Pull request by Bezmehrabi**
I added types for most of the things.

with these new type utilities, we will have much better type safety.
```ts
interface FormValues {
  name: string
  age: string
  friends: { name: string, family: string }[]
}

function MyInput() {
  const nameFieldState = useFieldState<FormValues>('name') // perfect! field exists.
  const wrongFieldState = useFieldState<FormValues>('nams') // oops, error! field doesn't exist.
  const friendNameState = useFieldState<FormValues>('friends.0.name') // works perfectly with nested fields! 

  return (
    ....
  )
}
```

unfortunately the [typescript partial type argument inference feature](https://github.com/microsoft/TypeScript/pull/26349) is yet to be added. so for the hooks like `useField` we have to write it like this for now (which is very sad):
```ts

function MyInput() {
  // we have to write the field name twice :(
 // because for now, typescript doesn't support  partial type argument inference, so we should either
// provide all the generic types, or let typescript infer all of them.
  const { fieldApi: { setValue }  } = useField<FormValues, 'name'>({ name: 'name' })

  const wrongArrayField = useArrayField<FormValues, 'age'>({ name: 'age' }) // oops! error, age isn't an array you can't use it.
  const arrayField = useArrayField<FormValues, 'friends'>({ name: 'friends' }) // perfect! friends is an array, so no problem amigo!

  const handleButtonClick=  () => {
      setValue('hello') // perfect!
      setValue(5) // oops! value should be string not number!.
  }
  
 return (
    ...
  )
}

```

I'm still working on types to make them even narrower which will result into an even better type safety. :)
but I feel like this is good enough to merge for now. so people can use it.

### CODE REVIEW

**Comment by joepuzzo** [comment]
In other words If you need these types to be this complex. Use your own type file in your project. Im super strict about this. Im aware I need to add missing types ( that part I would consider merging a PR on ) but I will not allow the types to become overly complex. If you ask 7 different typescript developers how to type this library they would make 7 completley different pull requests with different solutions and names for things.

**Comment by Bezmehrabi** [comment]
I mean, it's all about trade-offs. The code is more complex, so the DX is not great as it is with those simple types, but the typescript users will enjoy such safety.
That's what typescript is all about,  **Safety**.
So when the types are narrowed (which is achieved by writing some complex types), it will be harder to make a mistake when using the library.

**Comment by joepuzzo** [comment]
I 100% agree with you. But thats why I will export simple types and then TS users can do what they want with custom ones. I have spent LOTs of time going back and forth with TS peoples and every single one types this differently and does not like how the other typed it.  So im going to keep the internal ones simple. 

I am not a TS person, ( I can use it ), but I choose not to. 

Every single developer that has talked to me over the years says the same thing.

"Trust me you will like TS eventually"

Many have tried and none have succeeded. ( yes im stubborn  lol ). 

I did an experiment where I had 3 diff TS people type some parts of this lib and EVERY SINGLE one ( experienced in TS for years ) gave different types. So Im choosing to go dead simple route.

Again, if you want to maintain your own types that is totally doable so I would recommend that is the path.

**Comment by joepuzzo** [comment]
All this aside, yes even the dead simple types are not complete and i need to work to finish them. ( I am working on that now ) but trust me I have had these conversations over and over and over.

**Comment by joepuzzo** [comment]
And in my experience you gain "safety" for additional complexity. Things become more confusing ( more characters / more code, more stuff to read and understand )

**Comment by Bezmehrabi** [comment]
> And in my experience you gain "safety" for additional complexity. Things become more confusing ( more characters / more code, more stuff to read and understand )

the users won't see that complexity, it's you the library maintainer who sacrifices himself for the users.

overall, I'm totally agree with some of the things you said, and we will continue with the simple types.

I'll close this PR, but will probably make another simple PR just to add the missing types.

**Comment by joepuzzo** [comment]
Ok sounds good! Yes I really do apologize for being stubborn on TS. I think your other PR ( about showErrorIfTouched ) is good idea tho and will merge that next! and get it out.

**Pull request closed without merging**
